version: '3'

services:
  bluewing:
    image: bluewing/bluewing
    container_name: bluewing
    environment:
      PHP_IDE_CONFIG: serverName=bluewing
      XDEBUG_CONFIG: remote_host=192.168.86.115 remote_port=9003
    working_dir: /var/www
    expose:
      - "9000"
    volumes:
      - .:/var/www
      - ./infrastructure/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
